Issue/1
Kahuel/carder pull request #4
Opened 2022-07-21 16:39 UTC by Kahuel

2022-07-22 09:33 UTC, flymans commented
Коммитим одним коммитом. В таком виде: https://www.conventionalcommits.org/en/v1.0.0/

2022-07-22 09:37 UTC, flymans requested changes
[questions.txt](https://github.com/Kahuel/carder/pull/4/files#diff-c358a97e9613f03aab9b9b9f03480dd48b9155c18c5e232425d81b2a224cd52f)
Лишний файл, удали или добавь в gitignore, в гите он точно не нужен

2022-07-22 09:39 UTC, flymans commented on src/App.tsx
> +    <div style={{ height: "300px", width: "400px", background: "grey" }}>
Против inline style, давай отметим комментом, что потом переедем на css-in-js или по-другому //todo

2022-07-22 09:40 UTC, flymans commented on src/components/Enemy/Enemy.tsx
> +      <p>{enemy?.name}</p>
enemy может прилететь undefined?

2022-07-22 09:41 UTC, flymans commented on src/components/Player/Player.tsx
> +            disabled={enemy.hp < 1 || player.energy < actionsCost[actionName]}
Пока это норм читается, но боюсь что в дальнейшем усложнится логика, мб вынесем?

2022-07-22 09:58 UTC, flymans commented on src/components/actions/actions.ts
> +  regeneration: { heal: hp / 20 > 1 ? hp / 20 : 1, cost: 1 },
Сложно читается, давай в скобочки или hp / 20 в отдельную переменную

2022-07-22 10:03 UTC, flymans commented on src/state/models/combat.ts
> +      const { heal = 0, damage = 0, cost = 1 }: Action = actions(playerStrength, playerHP)[actionName];
Вот этот повторяющийся кусок кода я бы хотел вынести в отдельную функцию

2022-07-22 10:04 UTC, flymans commented on src/state/models/combat.ts
> +      const actionName = pattern[(state.combat.turn - 1) % pattern.length];
К комменту выше

2022-07-23 13:35 UTC, Kahuel commented on src/components/Enemy/Enemy.tsx
> +      <p>{enemy?.name}</p>
До нажатия кнопки начала сражения в enemy undefined.  В следующих коммитах поправлю.

2022-07-23 13:36 UTC, Kahuel commented on src/components/Player/Player.tsx
> +            disabled={enemy.hp < 1 || player.energy < actionsCost[actionName]}
По идее, сложнее не будет. Если только дизармы будем пилить или типа того.

2022-07-23 18:45 UTC, flymans commented on src/components/Player/Player.tsx
> +            disabled={enemy.hp < 1 || player.energy < actionsCost[actionName]}
Давай если усложнится - придумаем, пока норм

2022-07-26 13:45 UTC, Kahuel commented on src/App.tsx
> +    <div style={{ height: "300px", width: "400px", background: "grey" }}>
Забил. Вспомним

2022-07-26 13:46 UTC, Kahuel commented on src/components/actions/actions.ts
> +  regeneration: { heal: hp / 20 > 1 ? hp / 20 : 1, cost: 1 },
Вынес в отдельную функцию

2022-07-26 13:46 UTC, Kahuel commented on src/state/models/combat.ts
> +      const { heal = 0, damage = 0, cost = 1 }: Action = actions(playerStrength, playerHP)[actionName];
Вынес

2022-07-26 13:46 UTC, Kahuel commented on src/state/models/combat.ts
> +      const actionName = pattern[(state.combat.turn - 1) % pattern.length];
Чекни выше

2022-07-26 13:48 UTC, flymans approved these changes

2022-07-26 14:05 UTC, merged